---
- hosts: all
  become: yes

  vars:
    repository_version: "{{ release | replace('v', '') }}"

    enabled_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - "rhel-7-server-ose-{{ repository_version }}-rpms"

  tasks:

    - name: Load credentials
      include_vars: "../vars/credentials.yml"

    - name: Subscribe RHN
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ pool_id }}"

    - name: Disable HTB repository
      rhsm_repository:
        name: rhel-7-server-htb-rpms
        state: disabled

    - name: Enable repos
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      with_items: "{{ enabled_repos }}"

    - name: Ansible repository 2.6
      rhsm_repository:
        name: rhel-7-server-ansible-2.6-rpms
        state: enabled
      when: repository_version == '3.11'

    - name: Ansible repository 2.4
      rhsm_repository:
        name: rhel-7-server-ansible-2.4-rpms
        state: enabled
      when: repository_version == '3.10' or repository_version == '3.9'
